---
- name: Remove root SSH access
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin no"
    state: present

- name: Remove password SSH access
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
